title: Miscellaneous posts of Ferenc L치szl칩 Nagy
description: A place to post things to.
author: Ferenc L치szl칩 Nagy
remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
    - { platform: github,  user_url: "https://github.com/nfllab" }
    - { platform: mastodon, user_url: "https://infosec.exchange/@nflnfl" }
plugins:
  - jekyll-feed
